apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-night-fever-deployment
  namespace: card-night-fever-prod
  labels:
    app: card-night-fever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-night-fever
  template:
    metadata:
      labels:
        app: card-night-fever
    spec:
      containers:
        - name: web-server
          image: codegold79/card-night-fever:1.0.0
          resources:
            limits:
              cpu: 0.25
              memory: 250Mi
            requests:
              cpu: 0.25
              memory: 250Mi
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
